[tools]
node = "24.11"
neovim = "0.11"
fzf = "0.66"
ripgrep = "15.1"
bat = "0.26.0"
btop = "1.4"
yazi = "25.5"
starship = "1.24"
delta = "0.18"
lazygit = "0.56"
atuin = "18.10"
fd = "10.3"
zoxide = "latest"
eza = "latest"
vivid = "latest"
